@echo off
:: Self-elevate script if not running as admin
net session >nul 2>&1
if %errorLevel% neq 0 (
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

IF EXIST "C:\ProgramData\chocolatey\lib\vcredist2005" (
    echo Removing previous lock files for vcredist2005...
    rmdir /s /q "C:\ProgramData\chocolatey\lib\vcredist2005"
)

SETLOCAL
SET SCRIPT=%TEMP%\temp-setup.ps1
if exist "%SCRIPT%" del "%SCRIPT%" >nul
echo Set-ExecutionPolicy Bypass -Scope Process -Force>>"%SCRIPT%"
echo try { Set-ExecutionPolicy Bypass -Scope CurrentUser -Force -ErrorAction Stop } catch { Write-Host "Unable to set CurrentUser execution policy: $($_.Exception.Message)" -ForegroundColor Yellow }>>"%SCRIPT%"
echo try { Set-ExecutionPolicy Bypass -Scope LocalMachine -Force -ErrorAction Stop } catch { Write-Host "Unable to set LocalMachine execution policy: $($_.Exception.Message)" -ForegroundColor Yellow }>>"%SCRIPT%"
echo [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072>>"%SCRIPT%"
echo Write-Host "Starting Windows setup..." -ForegroundColor Cyan>>"%SCRIPT%"
echo if (Get-Command choco -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     Write-Host "Chocolatey already installed, skipping bootstrap..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing Chocolatey bootstrap..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     try {>>"%SCRIPT%"
echo         $chocoInstallScript = (Invoke-WebRequest -Uri "https://community.chocolatey.org/install.ps1" -UseBasicParsing -TimeoutSec 120).Content>>"%SCRIPT%"
echo         Invoke-Expression $chocoInstallScript>>"%SCRIPT%"
echo     } catch {>>"%SCRIPT%"
echo         throw "Chocolatey bootstrap failed: $($_.Exception.Message)">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo choco install googlechrome discord directx 7zip.install winrar vlc k-litecodecpackmega spotify handbrake sharex `>>"%SCRIPT%"
echo python notepadplusplus telegram.install pcloud rdm qbittorrent cloudflared warp winamp firefox putty winscp `>>"%SCRIPT%"
echo bleachbit bulk-crap-uninstaller wiztree streamlabs-obs eartrumpet git.install sourcetree `>>"%SCRIPT%"
echo vscode github-desktop gh ontopreplica onlyoffice nvm nvidia-app vcredist-all dotnet-6.0-desktopruntime `>>"%SCRIPT%"
echo dotnet-8.0-desktopruntime dotnet-9.0-desktopruntime dotnet-desktopruntime driverbooster protonvpn --ignore-checksums -y>>"%SCRIPT%"
echo if (Test-Path "$env:LOCALAPPDATA\DiscordCanary") { Write-Host "Discord Canary already installed, skipping..." -ForegroundColor Yellow } else {>>"%SCRIPT%"
echo     Write-Host "Installing Discord Canary..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $discordCanary = "$env:TEMP\DiscordCanarySetup.exe">>"%SCRIPT%"
echo     Invoke-WebRequest -Uri "https://discord.com/api/downloads/distributions/app/installers/latest?channel=canary&platform=win&arch=x64" -OutFile $discordCanary>>"%SCRIPT%"
echo     Start-Process -FilePath $discordCanary -ArgumentList "-s" -Wait>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo if (Test-Path "${env:ProgramFiles(x86)}\Google\Chrome Remote Desktop") { Write-Host "Chrome Remote Desktop already installed, skipping..." -ForegroundColor Yellow } else {>>"%SCRIPT%"
echo     Write-Host "Installing Chrome Remote Desktop..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $chromeRD = "$env:TEMP\chromeremotedesktophost.msi">>"%SCRIPT%"
echo     Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $chromeRD>>"%SCRIPT%"
echo     Start-Process msiexec.exe -ArgumentList "/i", $chromeRD, "/qn" -Wait>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo $iceInstalled = (Test-Path "$env:ProgramFiles\Icedrive\Icedrive.exe") -or (Test-Path "${env:ProgramFiles(x86)}\Icedrive\Icedrive.exe") -or (Test-Path "$env:LOCALAPPDATA\Programs\Icedrive\Icedrive.exe")>>"%SCRIPT%"
echo $dokanInstalled = (Test-Path "C:\Windows\System32\dokan2.dll") -or (Test-Path "C:\Windows\SysWOW64\dokan2.dll") -or (Test-Path "C:\Program Files\Dokan")>>"%SCRIPT%"
echo if ($iceInstalled -and $dokanInstalled) {>>"%SCRIPT%"
echo     Write-Host "IceDrive and Dokan already installed, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing IceDrive..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $iceInstaller = "$env:TEMP\IcedriveSetup.exe">>"%SCRIPT%"
echo     $iceReferrer = "https://icedrive.net/apps/desktop-laptop">>"%SCRIPT%"
echo     $ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)">>"%SCRIPT%"
echo     if (Test-Path $iceInstaller) { Remove-Item $iceInstaller -Force -ErrorAction SilentlyContinue }>>"%SCRIPT%"
echo     function Test-DokanInstalled {>>"%SCRIPT%"
echo         $dllPaths = @("C:\Windows\System32\dokan2.dll", "C:\Windows\SysWOW64\dokan2.dll")>>"%SCRIPT%"
echo         if ($dllPaths ^| Where-Object { Test-Path $_ }) { return $true }>>"%SCRIPT%"
echo         if (Test-Path "C:\Program Files\Dokan") { return $true }>>"%SCRIPT%"
echo         return $false>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     function Ensure-DokanInstalled {>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         Write-Host "Installing Dokan Library (required by IceDrive)..." -ForegroundColor Cyan>>"%SCRIPT%"
echo         try { winget install --id dokan-dev.Dokany -e --accept-source-agreements --accept-package-agreements --silent } catch { }>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         try { choco install dokany2 -y --ignore-checksums } catch { }>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         try {>>"%SCRIPT%"
echo             $release = Invoke-RestMethod "https://api.github.com/repos/dokan-dev/dokany/releases/latest">>"%SCRIPT%"
echo             $asset = $release.assets ^| Where-Object { $_.name -match '^DokanSetup_.*_x64\.msi$' } ^| Select-Object -First 1>>"%SCRIPT%"
echo             if ($asset) {>>"%SCRIPT%"
echo                 $dokanMsi = "$env:TEMP\DokanSetup.msi">>"%SCRIPT%"
echo                 ^& curl.exe -fL -o $dokanMsi $asset.browser_download_url --silent --show-error>>"%SCRIPT%"
echo                 Start-Process msiexec.exe -ArgumentList "/i", $dokanMsi, "/qn", "/norestart" -Wait>>"%SCRIPT%"
echo             }>>"%SCRIPT%"
echo         } catch { }>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         $svcState = (sc.exe query dokan2 2^>^$null ^| Out-String)>>"%SCRIPT%"
echo         $pending = Test-Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager">>"%SCRIPT%"
echo         if (($svcState -match "STOP_PENDING") -or ($pending -and ((Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue).PendingFileRenameOperations))) {>>"%SCRIPT%"
echo             throw "Dokan driver is pending removal/update. Restart Windows, then re-run this setup script.">>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo         throw "Unable to install Dokan Library automatically.">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     function Test-IceDriveInstaller([string]$path) {>>"%SCRIPT%"
echo         if (-not (Test-Path $path)) { return $false }>>"%SCRIPT%"
echo         try {>>"%SCRIPT%"
echo             $item = Get-Item $path -ErrorAction Stop>>"%SCRIPT%"
echo             if ($item.Length -lt 50000000) { return $false }>>"%SCRIPT%"
echo             $header = [System.IO.File]::ReadAllBytes($path)[0..1]>>"%SCRIPT%"
echo             if (($header[0] -ne 77) -or ($header[1] -ne 90)) { return $false }>>"%SCRIPT%"
echo             $sig = Get-AuthenticodeSignature $path>>"%SCRIPT%"
echo             if ($sig.Status -ne "Valid") { return $false }>>"%SCRIPT%"
echo             return $true>>"%SCRIPT%"
echo         } catch {>>"%SCRIPT%"
echo             return $false>>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     function Get-IceDriveInstaller([string]$url) {>>"%SCRIPT%"
echo         if (-not $url) { return $false }>>"%SCRIPT%"
echo         Write-Host "Downloading IceDrive installer from $url" -ForegroundColor Cyan>>"%SCRIPT%"
echo         try {>>"%SCRIPT%"
echo             ^& curl.exe -fL -A $ua -e $iceReferrer -o $iceInstaller $url --silent --show-error>>"%SCRIPT%"
echo         } catch {>>"%SCRIPT%"
echo             return $false>>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo         return (Test-IceDriveInstaller $iceInstaller)>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     $candidateUrls = @()>>"%SCRIPT%"
echo     try {>>"%SCRIPT%"
echo         $icePage = ^& curl.exe -fsSL -A $ua $iceReferrer>>"%SCRIPT%"
echo         $absolute = ([regex]::Matches($icePage, 'https://cdn\.icedrive\.net/static/apps/win/IcedriveSetup-v[\d.]+\.exe') ^| ForEach-Object { $_.Value }) ^| Select-Object -Unique>>"%SCRIPT%"
echo         if ($absolute) { $candidateUrls += $absolute }>>"%SCRIPT%"
echo         $relative = ([regex]::Matches($icePage, 'value="(win/IcedriveSetup-v[\d.]+\.exe)"') ^| ForEach-Object { $_.Groups[1].Value }) ^| Select-Object -Unique>>"%SCRIPT%"
echo         if ($relative) { $candidateUrls += ($relative ^| ForEach-Object { "https://cdn.icedrive.net/static/apps/$_" }) }>>"%SCRIPT%"
echo     } catch { }>>"%SCRIPT%"
echo     $candidateUrls += @("https://cdn.icedrive.net/static/apps/win/IcedriveSetup-v3.56.exe", "https://cdn.icedrive.net/static/apps/win/IcedriveSetup-v3.55.exe")>>"%SCRIPT%"
echo     $candidateUrls = $candidateUrls ^| Select-Object -Unique>>"%SCRIPT%"
echo     $ok = $false>>"%SCRIPT%"
echo     Ensure-DokanInstalled>>"%SCRIPT%"
echo     foreach ($candidate in $candidateUrls) {>>"%SCRIPT%"
echo         if (Get-IceDriveInstaller $candidate) { $ok = $true; break }>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     if (-not $ok) {>>"%SCRIPT%"
echo         Write-Host "IceDrive installer download failed validation." -ForegroundColor Red>>"%SCRIPT%"
echo         throw "IceDrive installer download failed validation.">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     Start-Process -FilePath $iceInstaller -ArgumentList "/S /NORESTART" -Wait>>"%SCRIPT%"
echo     Start-Sleep -Seconds ^3>>"%SCRIPT%"
echo     if (-not (Test-DokanInstalled)) {>>"%SCRIPT%"
echo         Write-Host "Dokan missing after IceDrive install. Repairing Dokan and retrying IceDrive..." -ForegroundColor Yellow>>"%SCRIPT%"
echo         Ensure-DokanInstalled>>"%SCRIPT%"
echo         Start-Process -FilePath $iceInstaller -ArgumentList "/S /NORESTART" -Wait>>"%SCRIPT%"
echo         Start-Sleep -Seconds ^3>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     $iceInstalled = (Test-Path "$env:ProgramFiles\Icedrive\Icedrive.exe") -or (Test-Path "${env:ProgramFiles(x86)}\Icedrive\Icedrive.exe") -or (Test-Path "$env:LOCALAPPDATA\Programs\Icedrive\Icedrive.exe")>>"%SCRIPT%"
echo     if (-not $iceInstalled) {>>"%SCRIPT%"
echo         throw "IceDrive installation finished but executable was not found.">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     if (-not (Test-DokanInstalled)) { throw "Dokan is still missing after automatic remediation." }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "Installing 2FAGuard..." -ForegroundColor Cyan>>"%SCRIPT%"
echo winget install --id timokoessler.2FAGuard -e --accept-source-agreements --accept-package-agreements --silent>>"%SCRIPT%"
echo Write-Host "Installing Claude Desktop..." -ForegroundColor Cyan>>"%SCRIPT%"
echo winget install --id Anthropic.Claude -e --accept-source-agreements --accept-package-agreements --silent>>"%SCRIPT%"
echo refreshenv 2^>^$null>>"%SCRIPT%"
echo nvm install lts 2^>^$null>>"%SCRIPT%"
echo nvm use lts 2^>^$null>>"%SCRIPT%"
echo if (Get-Command claude -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     Write-Host "Claude Code already installed, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing Claude Code..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     irm https://claude.ai/install.ps1 ^| iex>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo if (-not ($env:PATH -split ';' ^| Where-Object { $_ -eq "$env:USERPROFILE\.local\bin" })) {>>"%SCRIPT%"
echo     [Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable('PATH', 'User') + ";$env:USERPROFILE\.local\bin", 'User')>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo function Install-NpmGlobalPackage([string]$package, [string]$displayName) {>>"%SCRIPT%"
echo     $maxAttempts = 3 >>"%SCRIPT%"
echo     for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {>>"%SCRIPT%"
echo         Write-Host "Installing $displayName (attempt $attempt/$maxAttempts)..." -ForegroundColor Cyan>>"%SCRIPT%"
echo         $proc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c npm.cmd install -g $package --no-fund --no-audit" -Wait -NoNewWindow -PassThru>>"%SCRIPT%"
echo         if ($proc.ExitCode -eq 0) { return $true }>>"%SCRIPT%"
echo         Write-Host "$displayName install attempt failed with exit code $($proc.ExitCode)." -ForegroundColor Yellow>>"%SCRIPT%"
echo         Start-Sleep -Seconds (4 * $attempt)>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     Write-Host "$displayName installation failed after $maxAttempts attempts. Continuing setup." -ForegroundColor Yellow>>"%SCRIPT%"
echo     return $false>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo if (Get-Command codex -ErrorAction SilentlyContinue) { Write-Host "OpenAI Codex CLI already available, skipping npm global install..." -ForegroundColor Yellow } else { Install-NpmGlobalPackage "@openai/codex" "OpenAI Codex CLI" ^| Out-Null }>>"%SCRIPT%"
echo if (Get-Command copilot -ErrorAction SilentlyContinue) { Write-Host "GitHub Copilot CLI already available, skipping npm global install..." -ForegroundColor Yellow } else { Install-NpmGlobalPackage "@github/copilot" "GitHub Copilot CLI" ^| Out-Null }>>"%SCRIPT%"
echo Write-Host "Installing GitHub Copilot gh extension..." -ForegroundColor Cyan>>"%SCRIPT%"
echo $ghAuth = Start-Process -FilePath "cmd.exe" -ArgumentList "/c gh auth status >nul 2>nul" -Wait -NoNewWindow -PassThru>>"%SCRIPT%"
echo if ($ghAuth.ExitCode -eq 0) {>>"%SCRIPT%"
echo     $ghCopilotExt = Start-Process -FilePath "cmd.exe" -ArgumentList "/c gh extension list | findstr /i gh-copilot >nul || gh extension install github/gh-copilot" -Wait -NoNewWindow -PassThru>>"%SCRIPT%"
echo     if ($ghCopilotExt.ExitCode -ne 0) { Write-Host "gh-copilot extension install failed with exit code $($ghCopilotExt.ExitCode). Continuing setup." -ForegroundColor Yellow }>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "GitHub CLI is not authenticated; skipping gh-copilot extension install." -ForegroundColor Yellow>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "`n Setup complete." -ForegroundColor Green>>"%SCRIPT%"
echo if (Get-Command wsl -ErrorAction SilentlyContinue) { Write-Host "WSL already installed, skipping..." -ForegroundColor Yellow } else {>>"%SCRIPT%"
echo     Write-Host "Installing WSL..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     wsl --install --no-launch>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo if ((Get-Command wsl -ErrorAction SilentlyContinue) -and (wsl -l -q 2^>^$null)) {>>"%SCRIPT%"
echo     wsl -e bash -lc "[ -x ~/.local/bin/claude ]">>"%SCRIPT%"
echo     if ($LASTEXITCODE -eq 0) {>>"%SCRIPT%"
echo         Write-Host "Claude Code already installed in WSL, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo     } else {>>"%SCRIPT%"
echo         Write-Host "Installing Claude Code in WSL..." -ForegroundColor Cyan>>"%SCRIPT%"
echo         wsl -e bash -c "curl -fsSL https://claude.ai/install.sh | bash">>"%SCRIPT%"
echo         wsl -e bash -c "grep -q '.local/bin' ~/.bashrc || echo 'export PATH=\"\`$HOME/.local/bin:\`$PATH\"' >> ~/.bashrc">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo } else { Write-Host "WSL not ready yet - run this script again after restart to install Claude Code in WSL" -ForegroundColor Yellow }>>"%SCRIPT%"
echo Write-Host "`n All done! Restart your computer if WSL was installed." -ForegroundColor Green>>"%SCRIPT%"
powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%"
if %errorLevel% neq 0 (
    echo.
    echo Setup failed with exit code %errorLevel%.
    echo Generated script: %SCRIPT%
)
ENDLOCAL
