@echo off
:: Self-elevate script if not running as admin
net session >nul 2>&1
if %errorLevel% neq 0 (
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

IF EXIST "C:\ProgramData\chocolatey\lib\vcredist2005" (
    echo Removing previous lock files for vcredist2005...
    rmdir /s /q "C:\ProgramData\chocolatey\lib\vcredist2005"
)

SETLOCAL
SET SCRIPT=%TEMP%\temp-setup.ps1
if exist "%SCRIPT%" del "%SCRIPT%" >nul
echo Set-ExecutionPolicy Bypass -Scope Process -Force>>"%SCRIPT%"
echo try { Set-ExecutionPolicy Bypass -Scope CurrentUser -Force -ErrorAction Stop } catch { Write-Host "Unable to set CurrentUser execution policy: $($_.Exception.Message)" -ForegroundColor Yellow }>>"%SCRIPT%"
echo try { Set-ExecutionPolicy Bypass -Scope LocalMachine -Force -ErrorAction Stop } catch { Write-Host "Unable to set LocalMachine execution policy: $($_.Exception.Message)" -ForegroundColor Yellow }>>"%SCRIPT%"
echo [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072>>"%SCRIPT%"
echo function Install-DirectExe^([string]$name, [string]$url, [string]$silentArgs, [string]$installedPath^) {>>"%SCRIPT%"
echo     if ^(Test-Path $installedPath^) { Write-Host "$name already installed, skipping..." -ForegroundColor Yellow; return }>>"%SCRIPT%"
echo     Write-Host "Installing $name..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $tmp = $env:TEMP + '\' + ^($name -replace '\W', ''^) + 'Setup.exe'>>"%SCRIPT%"
echo     if ^(Test-Path $tmp^) { Remove-Item $tmp -Force -ErrorAction SilentlyContinue }>>"%SCRIPT%"
echo     curl.exe -L --progress-bar -o $tmp $url>>"%SCRIPT%"
echo     Start-Process -FilePath $tmp -ArgumentList $silentArgs -Wait>>"%SCRIPT%"
echo     if ^(-not ^(Test-Path $installedPath^)^) { throw "$name install finished but install path not found." }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo function Install-DirectMsi^([string]$name, [string]$url, [string]$installedPath^) {>>"%SCRIPT%"
echo     if ^(Test-Path $installedPath^) { Write-Host "$name already installed, skipping..." -ForegroundColor Yellow; return }>>"%SCRIPT%"
echo     Write-Host "Installing $name..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $tmp = $env:TEMP + '\' + ^($name -replace '\W', ''^) + 'Setup.msi'>>"%SCRIPT%"
echo     if ^(Test-Path $tmp^) { Remove-Item $tmp -Force -ErrorAction SilentlyContinue }>>"%SCRIPT%"
echo     curl.exe -L --progress-bar -o $tmp $url>>"%SCRIPT%"
echo     Start-Process msiexec.exe -ArgumentList "/i", $tmp, "/qn", "/norestart" -Wait>>"%SCRIPT%"
echo     if ^(-not ^(Test-Path $installedPath^)^) { throw "$name install finished but install path not found." }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "Starting Windows setup..." -ForegroundColor Cyan>>"%SCRIPT%"
echo if (Get-Command choco -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     Write-Host "Chocolatey already installed, skipping bootstrap..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing Chocolatey bootstrap..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     try {>>"%SCRIPT%"
echo         $chocoInstallScript = (Invoke-WebRequest -Uri "https://community.chocolatey.org/install.ps1" -UseBasicParsing -TimeoutSec 120).Content>>"%SCRIPT%"
echo         Invoke-Expression $chocoInstallScript>>"%SCRIPT%"
echo     } catch {>>"%SCRIPT%"
echo         throw "Chocolatey bootstrap failed: $($_.Exception.Message)">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo choco install googlechrome discord directx 7zip.install winrar vlc k-litecodecpackmega spotify handbrake sharex `>>"%SCRIPT%"
echo python notepadplusplus telegram.install pcloud rdm qbittorrent cloudflared warp winamp firefox putty winscp `>>"%SCRIPT%"
echo bleachbit bulk-crap-uninstaller wiztree eartrumpet git.install sourcetree `>>"%SCRIPT%"
echo vscode github-desktop gh ontopreplica onlyoffice nvidia-app protonvpn --ignore-checksums -y>>"%SCRIPT%"
echo choco install vcredist-all dotnet-6.0-desktopruntime dotnet-8.0-desktopruntime dotnet-9.0-desktopruntime dotnet-desktopruntime -y>>"%SCRIPT%"
echo choco install streamlabs-obs -y>>"%SCRIPT%"
echo Write-Host "Installing JetBrainsMono Nerd Font..." -ForegroundColor Cyan>>"%SCRIPT%"
echo choco install nerd-fonts-jetbrainsmono -y>>"%SCRIPT%"
echo Install-DirectExe "Discord Canary" "https://discord.com/api/download/canary?platform=win" "/S" "$env:LOCALAPPDATA\DiscordCanary">>"%SCRIPT%"
echo Install-DirectMsi "Chrome Remote Desktop" "https://dl.google.com/dl/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" "${env:ProgramFiles(x86)}\Google\Chrome Remote Desktop">>"%SCRIPT%"
echo $mudfishInstalled = (Test-Path "${env:ProgramFiles(x86)}\Mudfish Cloud VPN\mudfish.exe") -or (Test-Path "$env:ProgramFiles\Mudfish Cloud VPN\mudfish.exe") -or (Test-Path "$env:LOCALAPPDATA\Mudfish Cloud VPN\mudfish.exe")>>"%SCRIPT%"
echo if ($mudfishInstalled) {>>"%SCRIPT%"
echo     Write-Host "Mudfish already installed, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing Mudfish..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $mudfishPage = ^& curl.exe -fsSL "https://mudfish.net/download">>"%SCRIPT%"
echo     $mudfishPath = $null>>"%SCRIPT%"
echo     $mudfishMatch = [regex]::Match($mudfishPage, '/download\?filename=mudfish-[0-9.]+-x86_64-win2k-setup\.exe')>>"%SCRIPT%"
echo     if ($mudfishMatch.Success) { $mudfishPath = $mudfishMatch.Value }>>"%SCRIPT%"
echo     if (-not $mudfishPath) { throw "Mudfish Windows installer link not found." }>>"%SCRIPT%"
echo     $mudfishFile = $mudfishPath -replace '^/download\?filename=', ''>>"%SCRIPT%"
echo     $mudfishUrl = "https://mudfish.net/releases/$mudfishFile">>"%SCRIPT%"
echo     Install-DirectExe "Mudfish" $mudfishUrl "/S" "${env:ProgramFiles(x86)}\Mudfish Cloud VPN">>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo $iceInstalled = (Test-Path "$env:ProgramFiles\Icedrive\Icedrive.exe") -or (Test-Path "${env:ProgramFiles(x86)}\Icedrive\Icedrive.exe") -or (Test-Path "$env:LOCALAPPDATA\Programs\Icedrive\Icedrive.exe")>>"%SCRIPT%"
echo $dokanInstalled = (Test-Path "C:\Windows\System32\dokan2.dll") -or (Test-Path "C:\Windows\SysWOW64\dokan2.dll") -or (Test-Path "C:\Program Files\Dokan")>>"%SCRIPT%"
echo if ($iceInstalled -and $dokanInstalled) {>>"%SCRIPT%"
echo     Write-Host "IceDrive and Dokan already installed, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing IceDrive..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $iceInstaller = "$env:TEMP\IcedriveSetup.exe">>"%SCRIPT%"
echo     $iceReferrer = "https://icedrive.net/apps/desktop-laptop">>"%SCRIPT%"
echo     $ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)">>"%SCRIPT%"
echo     if (Test-Path $iceInstaller) { Remove-Item $iceInstaller -Force -ErrorAction SilentlyContinue }>>"%SCRIPT%"
echo     function Test-DokanInstalled {>>"%SCRIPT%"
echo         $dllPaths = @("C:\Windows\System32\dokan2.dll", "C:\Windows\SysWOW64\dokan2.dll")>>"%SCRIPT%"
echo         if ($dllPaths ^| Where-Object { Test-Path $_ }) { return $true }>>"%SCRIPT%"
echo         if (Test-Path "C:\Program Files\Dokan") { return $true }>>"%SCRIPT%"
echo         return $false>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     function Ensure-DokanInstalled {>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         Write-Host "Installing Dokan Library (required by IceDrive)..." -ForegroundColor Cyan>>"%SCRIPT%"
echo         try { winget install --id dokan-dev.Dokany -e --accept-source-agreements --accept-package-agreements --silent } catch { }>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         try { choco install dokany2 -y --ignore-checksums } catch { }>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         try {>>"%SCRIPT%"
echo             $release = Invoke-RestMethod "https://api.github.com/repos/dokan-dev/dokany/releases/latest">>"%SCRIPT%"
echo             $asset = $release.assets ^| Where-Object { $_.name -match '^DokanSetup_.*_x64\.msi$' } ^| Select-Object -First 1 >>"%SCRIPT%"
echo             if ($asset) {>>"%SCRIPT%"
echo                 $dokanMsi = "$env:TEMP\DokanSetup.msi">>"%SCRIPT%"
echo                 ^& curl.exe -fL -o $dokanMsi $asset.browser_download_url --silent --show-error>>"%SCRIPT%"
echo                 Start-Process msiexec.exe -ArgumentList "/i", $dokanMsi, "/qn", "/norestart" -Wait>>"%SCRIPT%"
echo             }>>"%SCRIPT%"
echo         } catch { }>>"%SCRIPT%"
echo         if (Test-DokanInstalled) { return $true }>>"%SCRIPT%"
echo         $svcState = (sc.exe query dokan2 2^>^$null ^| Out-String)>>"%SCRIPT%"
echo         $pending = Test-Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager">>"%SCRIPT%"
echo         if (($svcState -match "STOP_PENDING") -or ($pending -and ((Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue).PendingFileRenameOperations))) {>>"%SCRIPT%"
echo             throw "Dokan driver is pending removal/update. Restart Windows, then re-run this setup script.">>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo         throw "Unable to install Dokan Library automatically.">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     function Test-IceDriveInstaller([string]$path) {>>"%SCRIPT%"
echo         if (-not (Test-Path $path)) { return $false }>>"%SCRIPT%"
echo         try {>>"%SCRIPT%"
echo             $item = Get-Item $path -ErrorAction Stop>>"%SCRIPT%"
echo             if ($item.Length -lt 50000000) { return $false }>>"%SCRIPT%"
echo             $header = [System.IO.File]::ReadAllBytes($path)[0..1]>>"%SCRIPT%"
echo             if (($header[0] -ne 77) -or ($header[1] -ne 90)) { return $false }>>"%SCRIPT%"
echo             $sig = Get-AuthenticodeSignature $path>>"%SCRIPT%"
echo             if ($sig.Status -ne "Valid") { return $false }>>"%SCRIPT%"
echo             return $true>>"%SCRIPT%"
echo         } catch {>>"%SCRIPT%"
echo             return $false>>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     function Get-IceDriveInstaller([string]$url) {>>"%SCRIPT%"
echo         if (-not $url) { return $false }>>"%SCRIPT%"
echo         Write-Host "Downloading IceDrive installer from $url" -ForegroundColor Cyan>>"%SCRIPT%"
echo         try {>>"%SCRIPT%"
echo             ^& curl.exe -fL -A $ua -e $iceReferrer -o $iceInstaller $url --silent --show-error>>"%SCRIPT%"
echo         } catch {>>"%SCRIPT%"
echo             return $false>>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo         return (Test-IceDriveInstaller $iceInstaller)>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     $candidateUrls = @()>>"%SCRIPT%"
echo     try {>>"%SCRIPT%"
echo         $icePage = ^& curl.exe -fsSL -A $ua $iceReferrer>>"%SCRIPT%"
echo         $absolute = ([regex]::Matches($icePage, 'https://cdn\.icedrive\.net/static/apps/win/IcedriveSetup-v[\d.]+\.exe') ^| ForEach-Object { $_.Value }) ^| Select-Object -Unique>>"%SCRIPT%"
echo         if ($absolute) { $candidateUrls += $absolute }>>"%SCRIPT%"
echo         $relative = ([regex]::Matches($icePage, 'value="(win/IcedriveSetup-v[\d.]+\.exe)"') ^| ForEach-Object { $_.Groups[1].Value }) ^| Select-Object -Unique>>"%SCRIPT%"
echo         if ($relative) { $candidateUrls += ($relative ^| ForEach-Object { "https://cdn.icedrive.net/static/apps/$_" }) }>>"%SCRIPT%"
echo     } catch { }>>"%SCRIPT%"
echo     $candidateUrls += @("https://cdn.icedrive.net/static/apps/win/IcedriveSetup-v3.56.exe", "https://cdn.icedrive.net/static/apps/win/IcedriveSetup-v3.55.exe")>>"%SCRIPT%"
echo     $candidateUrls = $candidateUrls ^| Select-Object -Unique>>"%SCRIPT%"
echo     $ok = $false>>"%SCRIPT%"
echo     Ensure-DokanInstalled>>"%SCRIPT%"
echo     foreach ($candidate in $candidateUrls) {>>"%SCRIPT%"
echo         if (Get-IceDriveInstaller $candidate) { $ok = $true; break }>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     if (-not $ok) {>>"%SCRIPT%"
echo         Write-Host "IceDrive installer download failed validation." -ForegroundColor Red>>"%SCRIPT%"
echo         throw "IceDrive installer download failed validation.">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     Start-Process -FilePath $iceInstaller -ArgumentList "/S /NORESTART" -Wait>>"%SCRIPT%"
echo     if (-not (Test-DokanInstalled)) {>>"%SCRIPT%"
echo         Write-Host "Dokan missing after IceDrive install. Repairing Dokan and retrying IceDrive..." -ForegroundColor Yellow>>"%SCRIPT%"
echo         Ensure-DokanInstalled>>"%SCRIPT%"
echo         Start-Process -FilePath $iceInstaller -ArgumentList "/S /NORESTART" -Wait>>"%SCRIPT%"
echo         Start-Sleep -Seconds ^3>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     $iceInstalled = (Test-Path "$env:ProgramFiles\Icedrive\Icedrive.exe") -or (Test-Path "${env:ProgramFiles(x86)}\Icedrive\Icedrive.exe") -or (Test-Path "$env:LOCALAPPDATA\Programs\Icedrive\Icedrive.exe")>>"%SCRIPT%"
echo     if (-not $iceInstalled) {>>"%SCRIPT%"
echo         throw "IceDrive installation finished but executable was not found.">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     if (-not (Test-DokanInstalled)) { throw "Dokan is still missing after automatic remediation." }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "Installing 2FAGuard..." -ForegroundColor Cyan>>"%SCRIPT%"
echo winget install --id timokoessler.2FAGuard -e --accept-source-agreements --accept-package-agreements --silent>>"%SCRIPT%"
echo Write-Host "Installing Claude Desktop..." -ForegroundColor Cyan>>"%SCRIPT%"
echo winget install --id Anthropic.Claude -e --accept-source-agreements --accept-package-agreements --silent>>"%SCRIPT%"
echo Write-Host "Installing Kiro..." -ForegroundColor Cyan>>"%SCRIPT%"
echo winget install --id Amazon.Kiro -e --accept-source-agreements --accept-package-agreements --silent>>"%SCRIPT%"
echo Write-Host "Installing Rufus..." -ForegroundColor Cyan>>"%SCRIPT%"
echo winget install --id Rufus.Rufus -e --accept-source-agreements --accept-package-agreements --silent>>"%SCRIPT%"
echo Write-Host "Installing PowerShell 7..." -ForegroundColor Cyan>>"%SCRIPT%"
echo if ^(Get-Command pwsh -ErrorAction SilentlyContinue^) { Write-Host "PowerShell 7 already installed, skipping..." -ForegroundColor Yellow } else { winget install --id Microsoft.PowerShell -e --accept-source-agreements --accept-package-agreements --silent }>>"%SCRIPT%"
echo Write-Host "Installing WezTerm..." -ForegroundColor Cyan>>"%SCRIPT%"
echo if ^(Test-Path "$env:LOCALAPPDATA\Programs\WezTerm\wezterm-gui.exe"^) { Write-Host "WezTerm already installed, skipping..." -ForegroundColor Yellow } else { winget install --id wez.wezterm -e --accept-source-agreements --accept-package-agreements --silent }>>"%SCRIPT%"
echo Write-Host "Deploying .wezterm.lua config..." -ForegroundColor Cyan>>"%SCRIPT%"
echo if ^(-not ^(Test-Path "$env:USERPROFILE\.wezterm.lua"^)^) {>>"%SCRIPT%"
echo     $luaB64 = 'bG9jYWwgd2V6dGVybSA9IHJlcXVpcmUgJ3dlenRlcm0nCmxvY2FsIGNvbmZpZyA9IHdlenRlcm0uY29uZmlnX2J1aWxkZXIoKQoKY29uZmlnLnRlcm0gPSAneHRlcm0tMjU2Y29sb3InCmNvbmZpZy5zY3JvbGxiYWNrX2xpbmVzID0gMTAwMDAKCmNvbmZpZy5mb250ID0gd2V6dGVybS5mb250KCdKZXRCcmFpbnNNb25vIE5lcmQgRm9udCcpCmNvbmZpZy5mb250X3NpemUgPSAxMi4wCgpjb25maWcuY29sb3Jfc2NoZW1lID0gJ0NhdHBwdWNjaW4gTW9jaGEnCmNvbmZpZy53aW5kb3dfYmFja2dyb3VuZF9vcGFjaXR5ID0gMC45NQpjb25maWcudGV4dF9iYWNrZ3JvdW5kX29wYWNpdHkgPSAxLjAKY29uZmlnLndpbmRvd19kZWNvcmF0aW9ucyA9ICdSRVNJWkUnCgpjb25maWcuYXVkaWJsZV9iZWxsID0gJ0Rpc2FibGVkJwpjb25maWcudmlzdWFsX2JlbGwgPSB7CiAgZmFkZV9pbl9kdXJhdGlvbl9tcyA9IDc1LAogIGZhZGVfb3V0X2R1cmF0aW9uX21zID0gNzUsCiAgdGFyZ2V0ID0gJ0N1cnNvckNvbG9yJywKfQoKY29uZmlnLmRlZmF1bHRfcHJvZyA9IHsgJ3B3c2guZXhlJywgJy1Ob0xvZ28nIH0KY29uZmlnLmxhdW5jaF9tZW51ID0gewogIHsgbGFiZWwgPSAnUG93ZXJTaGVsbCA3JywgIGFyZ3MgPSB7ICdwd3NoLmV4ZScsICctTm9Mb2dvJyB9IH0sCiAgeyBsYWJlbCA9ICdQb3dlclNoZWxsIDUnLCAgYXJncyA9IHsgJ3Bvd2Vyc2hlbGwuZXhlJywgJy1Ob0xvZ28nIH0gfSwKICB7IGxhYmVsID0gJ0NNRCcsICAgICAgICAgICBhcmdzID0geyAnY21kLmV4ZScgfSB9LAogIHsgbGFiZWwgPSAnR2l0IEJhc2gnLCAgICAgIGFyZ3MgPSB7ICdDOlxcUHJvZ3JhbSBGaWxlc1xcR2l0XFxiaW5cXGJhc2guZXhlJywgJy1pJywgJy1sJyB9IH0sCiAgeyBsYWJlbCA9ICdXU0wnLCAgICAgICAgICAgYXJncyA9IHsgJ3dzbC5leGUnIH0gfSwKfQoKY29uZmlnLmtleXMgPSB7CiAgeyBrZXkgPSAndCcsIG1vZHMgPSAnQ1RSTHxTSElGVCcsIGFjdGlvbiA9IHdlenRlcm0uYWN0aW9uLlNwYXduVGFiICdDdXJyZW50UGFuZURvbWFpbicgfSwKICB7IGtleSA9ICd3JywgbW9kcyA9ICdDVFJMfFNISUZUJywgYWN0aW9uID0gd2V6dGVybS5hY3Rpb24uQ2xvc2VDdXJyZW50VGFiIHsgY29uZmlybSA9IGZhbHNlIH0gfSwKICB7IGtleSA9ICdkJywgbW9kcyA9ICdDVFJMfFNISUZUJywgYWN0aW9uID0gd2V6dGVybS5hY3Rpb24uU3BsaXRIb3Jpem9udGFsIHsgZG9tYWluID0gJ0N1cnJlbnRQYW5lRG9tYWluJyB9IH0sCiAgeyBrZXkgPSAnZScsIG1vZHMgPSAnQ1RSTHxTSElGVCcsIGFjdGlvbiA9IHdlenRlcm0uYWN0aW9uLlNwbGl0VmVydGljYWwgICB7IGRvbWFpbiA9ICdDdXJyZW50UGFuZURvbWFpbicgfSB9LAogIHsga2V5ID0gJ0xlZnRBcnJvdycsICBtb2RzID0gJ0NUUkx8U0hJRlQnLCBhY3Rpb24gPSB3ZXp0ZXJtLmFjdGlvbi5BY3RpdmF0ZVBhbmVEaXJlY3Rpb24gJ0xlZnQnIH0sCiAgeyBrZXkgPSAnUmlnaHRBcnJvdycsIG1vZHMgPSAnQ1RSTHxTSElGVCcsIGFjdGlvbiA9IHdlenRlcm0uYWN0aW9uLkFjdGl2YXRlUGFuZURpcmVjdGlvbiAnUmlnaHQnIH0sCiAgeyBrZXkgPSAnVXBBcnJvdycsICAgIG1vZHMgPSAnQ1RSTHxTSElGVCcsIGFjdGlvbiA9IHdlenRlcm0uYWN0aW9uLkFjdGl2YXRlUGFuZURpcmVjdGlvbiAnVXAnIH0sCiAgeyBrZXkgPSAnRG93bkFycm93JywgIG1vZHMgPSAnQ1RSTHxTSElGVCcsIGFjdGlvbiA9IHdlenRlcm0uYWN0aW9uLkFjdGl2YXRlUGFuZURpcmVjdGlvbiAnRG93bicgfSwKfQoKcmV0dXJuIGNvbmZpZw=='>>"%SCRIPT%"
echo     $luaContent = [System.Text.Encoding]::UTF8.GetString^([Convert]::FromBase64String^($luaB64^)^)>>"%SCRIPT%"
echo     [System.IO.File]::WriteAllText^("$env:USERPROFILE\.wezterm.lua", $luaContent, [System.Text.Encoding]::UTF8^)>>"%SCRIPT%"
echo     Write-Host ".wezterm.lua written to $env:USERPROFILE" -ForegroundColor Green>>"%SCRIPT%"
echo } else { Write-Host ".wezterm.lua already exists, skipping..." -ForegroundColor Yellow }>>"%SCRIPT%"
echo Write-Host "Configuring PowerShell profile for WezTerm notifications..." -ForegroundColor Cyan>>"%SCRIPT%"
echo if ^(-not ^(Test-Path $PROFILE^)^) { New-Item -Path $PROFILE -ItemType File -Force ^| Out-Null }>>"%SCRIPT%"
echo $profileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue>>"%SCRIPT%"
echo if ^($profileContent -notmatch '# WezTerm bell notification'^) {>>"%SCRIPT%"
echo     $profB64 = 'CiMgV2V6VGVybSBiZWxsIG5vdGlmaWNhdGlvbgokZ2xvYmFsOl9XZXpQcm9tcHRUaW1lciA9ICRudWxsCmZ1bmN0aW9uIHByb21wdCB7CiAgICAkbGFzdEV4aXQgPSAkTEFTVEVYSVRDT0RFCiAgICBpZiAoJGdsb2JhbDpfV2V6UHJvbXB0VGltZXIgLW5lICRudWxsKSB7CiAgICAgICAgJGVsYXBzZWQgPSAoR2V0LURhdGUpIC0gJGdsb2JhbDpfV2V6UHJvbXB0VGltZXIKICAgICAgICBpZiAoJGVsYXBzZWQuVG90YWxTZWNvbmRzIC1nZSAxMCkgewogICAgICAgICAgICBbQ29uc29sZV06OldyaXRlKCJgYSIpCiAgICAgICAgICAgIHRyeSB7CiAgICAgICAgICAgICAgICAkYXBwSWQgPSAnezFBQzE0RTc3LTAyRTctNEU1RC1CNzQ0LTJFQjFBRTUxOThCN31cV2luZG93c1Bvd2VyU2hlbGxcdjEuMFxwb3dlcnNoZWxsLmV4ZScKICAgICAgICAgICAgICAgICRzdGF0dXMgPSBpZiAoJGxhc3RFeGl0IC1lcSAwKSB7ICdmaW5pc2hlZCcgfSBlbHNlIHsgImZhaWxlZCAoZXhpdCAkbGFzdEV4aXQpIiB9CiAgICAgICAgICAgICAgICAkbXNnID0gIkNvbW1hbmQgJHN0YXR1cyBhZnRlciAkKFtpbnRdJGVsYXBzZWQuVG90YWxTZWNvbmRzKXMiCiAgICAgICAgICAgICAgICAkeG1sID0gW1dpbmRvd3MuRGF0YS5YbWwuRG9tLlhtbERvY3VtZW50LCBXaW5kb3dzLkRhdGEuWG1sLkRvbSwgQ29udGVudFR5cGU9V2luZG93c1J1bnRpbWVdOjpuZXcoKQogICAgICAgICAgICAgICAgJHhtbC5Mb2FkWG1sKCI8dG9hc3Q+PHZpc3VhbD48YmluZGluZyB0ZW1wbGF0ZT0nVG9hc3RUZXh0MDEnPjx0ZXh0IGlkPScxJz4kbXNnPC90ZXh0PjwvYmluZGluZz48L3Zpc3VhbD48L3RvYXN0PiIpCiAgICAgICAgICAgICAgICAkdG9hc3QgPSBbV2luZG93cy5VSS5Ob3RpZmljYXRpb25zLlRvYXN0Tm90aWZpY2F0aW9uLCBXaW5kb3dzLlVJLk5vdGlmaWNhdGlvbnMsIENvbnRlbnRUeXBlPVdpbmRvd3NSdW50aW1lXTo6bmV3KCR4bWwpCiAgICAgICAgICAgICAgICBbV2luZG93cy5VSS5Ob3RpZmljYXRpb25zLlRvYXN0Tm90aWZpY2F0aW9uTWFuYWdlciwgV2luZG93cy5VSS5Ob3RpZmljYXRpb25zLCBDb250ZW50VHlwZT1XaW5kb3dzUnVudGltZV06OkNyZWF0ZVRvYXN0Tm90aWZpZXIoJGFwcElkKS5TaG93KCR0b2FzdCkKICAgICAgICAgICAgfSBjYXRjaCB7IH0KICAgICAgICB9CiAgICB9CiAgICAkZ2xvYmFsOl9XZXpQcm9tcHRUaW1lciA9IEdldC1EYXRlCiAgICAkZ2xvYmFsOkxBU1RFWElUQ09ERSA9ICRsYXN0RXhpdAogICAgIlBTICQoJGV4ZWN1dGlvbkNvbnRleHQuU2Vzc2lvblN0YXRlLlBhdGguQ3VycmVudExvY2F0aW9uKSQoJz4nICogKCRuZXN0ZWRQcm9tcHRMZXZlbCArIDEpKSAiCn0='>>"%SCRIPT%"
echo     $profBlock = [System.Text.Encoding]::UTF8.GetString^([Convert]::FromBase64String^($profB64^)^)>>"%SCRIPT%"
echo     Add-Content -Path $PROFILE -Value $profBlock -Encoding UTF8>>"%SCRIPT%"
echo     Write-Host "WezTerm notification block added to PowerShell profile." -ForegroundColor Green>>"%SCRIPT%"
echo } else { Write-Host "WezTerm notification already in PS profile, skipping..." -ForegroundColor Yellow }>>"%SCRIPT%"
echo $rufusPackageDir = Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Packages\Rufus.Rufus_Microsoft.Winget.Source_8wekyb3d8bbwe">>"%SCRIPT%"
echo $rufusExe = Join-Path $rufusPackageDir "rufus.exe">>"%SCRIPT%"
echo if (Test-Path $rufusExe) {>>"%SCRIPT%"
echo     $desktopPath = [Environment]::GetFolderPath('Desktop')>>"%SCRIPT%"
echo     $rufusShortcut = Join-Path $desktopPath "Rufus.lnk">>"%SCRIPT%"
echo     $wshShell = New-Object -ComObject WScript.Shell>>"%SCRIPT%"
echo     $shortcut = $wshShell.CreateShortcut($rufusShortcut)>>"%SCRIPT%"
echo     $shortcut.TargetPath = $rufusExe>>"%SCRIPT%"
echo     $shortcut.WorkingDirectory = Split-Path $rufusExe>>"%SCRIPT%"
echo     $shortcut.IconLocation = "$rufusExe,0">>"%SCRIPT%"
echo     $shortcut.Save()>>"%SCRIPT%"
echo     Write-Host "Rufus desktop shortcut created." -ForegroundColor Green>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Rufus executable not found after install; skipping desktop shortcut." -ForegroundColor Yellow>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo $userPath = [Environment]::GetEnvironmentVariable('PATH', 'User')>>"%SCRIPT%"
echo if (-not ($userPath -split ';' ^| Where-Object { $_ -eq "$env:USERPROFILE\.local\bin" })) {>>"%SCRIPT%"
echo     [Environment]::SetEnvironmentVariable('PATH', $userPath + ";$env:USERPROFILE\.local\bin", 'User')>>"%SCRIPT%"
echo     $env:PATH = $env:PATH + ";$env:USERPROFILE\.local\bin">>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo if (Get-Command claude -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     Write-Host "Claude Code already installed, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing Claude Code..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     irm https://claude.ai/install.ps1 ^| iex>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "`n Setup complete." -ForegroundColor Green>>"%SCRIPT%"
echo if (Get-Command wsl -ErrorAction SilentlyContinue) { Write-Host "WSL already installed, skipping..." -ForegroundColor Yellow } else {>>"%SCRIPT%"
echo     Write-Host "Installing WSL..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     wsl --install --no-launch>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo $wslReady = $false>>"%SCRIPT%"
echo $wslSkipReason = $null>>"%SCRIPT%"
echo if (Get-Command wsl -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     try {>>"%SCRIPT%"
echo         $wslDistros = ^& wsl -l -q 2^>^$null>>"%SCRIPT%"
echo         $linuxDistros = @($wslDistros ^| ForEach-Object { ($_.ToString() -replace '\x00', '').Trim() } ^| Where-Object { $_ -and $_ -notmatch '^docker-desktop(-data)?$' })>>"%SCRIPT%"
echo         if ($linuxDistros.Count -gt 0) { $wslReady = $true } else { $wslSkipReason = "No Linux WSL distro is installed yet" }>>"%SCRIPT%"
echo     } catch { $wslSkipReason = "WSL check failed: $($_.Exception.Message)" }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo if ($wslReady) {>>"%SCRIPT%"
echo     $wslDistro = $linuxDistros ^| Select-Object -First 1 >>"%SCRIPT%"
echo     wsl -d $wslDistro -e bash -lc "[ -x ~/.local/bin/claude ]">>"%SCRIPT%"
echo     if ($LASTEXITCODE -eq 0) {>>"%SCRIPT%"
echo         Write-Host "Claude Code already installed in WSL, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo     } else {>>"%SCRIPT%"
echo         Write-Host "Installing Claude Code in WSL..." -ForegroundColor Cyan>>"%SCRIPT%"
echo         wsl -d $wslDistro -e bash -c "curl -fsSL https://claude.ai/install.sh | bash">>"%SCRIPT%"
echo         wsl -d $wslDistro -e bash -c "grep -q '.local/bin' ~/.bashrc || echo 'export PATH=\"\`$HOME/.local/bin:\`$PATH\"' >> ~/.bashrc">>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo } else { if ($wslSkipReason) { Write-Host "$wslSkipReason - skipping WSL setup." -ForegroundColor Yellow } else { Write-Host "WSL not ready yet - skipping WSL setup." -ForegroundColor Yellow } }>>"%SCRIPT%"
echo Write-Host "`n All done! Restart your computer if WSL was installed." -ForegroundColor Green>>"%SCRIPT%"
powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%"
if %errorLevel% neq 0 (
    echo.
    echo Setup failed with exit code %errorLevel%.
    echo Generated script: %SCRIPT%
)
ENDLOCAL
