@echo off
:: Auto-elevate to Administrator
net session >nul 2>&1
if %errorlevel% neq 0 (
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

setlocal
set "SCRIPT=%TEMP%\temp-node-setup.ps1"
if exist "%SCRIPT%" del "%SCRIPT%" >nul
echo Set-ExecutionPolicy Bypass -Scope Process -Force>>"%SCRIPT%"
echo [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072>>"%SCRIPT%"
echo function Refresh-SetupEnvironment {>>"%SCRIPT%"
echo     $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')>>"%SCRIPT%"
echo     $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')>>"%SCRIPT%"
echo     $pathParts = @($machinePath, $userPath) ^| Where-Object { -not [string]::IsNullOrWhiteSpace($_) }>>"%SCRIPT%"
echo     $env:Path = ($pathParts -join ';')>>"%SCRIPT%"
echo     foreach ($scope in 'Machine', 'User') {>>"%SCRIPT%"
echo         foreach ($name in 'NVM_HOME', 'NVM_SYMLINK') {>>"%SCRIPT%"
echo             $value = [Environment]::GetEnvironmentVariable($name, $scope)>>"%SCRIPT%"
echo             if (-not [string]::IsNullOrWhiteSpace($value)) { Set-Item -Path "Env:$name" -Value $value }>>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     $refreshEnvCmd = Get-Command refreshenv -ErrorAction SilentlyContinue>>"%SCRIPT%"
echo     if ($refreshEnvCmd) { ^& $refreshEnvCmd.Path 1^>^$null 2^>^$null }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo function Install-NpmGlobalPackage([string]$package, [string]$displayName) {>>"%SCRIPT%"
echo     $maxAttempts = 3>>"%SCRIPT%"
echo     for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {>>"%SCRIPT%"
echo         Write-Host "Installing $displayName (attempt $attempt/$maxAttempts)..." -ForegroundColor Cyan>>"%SCRIPT%"
echo         $proc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c npm.cmd install -g $package --no-fund --no-audit" -Wait -NoNewWindow -PassThru>>"%SCRIPT%"
echo         if ($proc.ExitCode -eq 0) { return $true }>>"%SCRIPT%"
echo         Write-Host "$displayName install attempt failed with exit code $($proc.ExitCode)." -ForegroundColor Yellow>>"%SCRIPT%"
echo         Start-Sleep -Seconds (4 * $attempt)>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo     Write-Host "$displayName installation failed after $maxAttempts attempts. Continuing setup." -ForegroundColor Yellow>>"%SCRIPT%"
echo     return $false>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "Starting Node.js setup..." -ForegroundColor Cyan>>"%SCRIPT%"
echo Refresh-SetupEnvironment>>"%SCRIPT%"
echo if (Get-Command nvm -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     Write-Host "nvm already installed, skipping Chocolatey install..." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing nvm..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     choco install nvm -y>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Refresh-SetupEnvironment>>"%SCRIPT%"
echo if (-not (Get-Command nvm -ErrorAction SilentlyContinue)) { throw "nvm is not available after installation." }>>"%SCRIPT%"
echo Write-Host "Installing Node.js LTS via nvm..." -ForegroundColor Cyan>>"%SCRIPT%"
echo nvm install lts 2^>^$null>>"%SCRIPT%"
echo Refresh-SetupEnvironment>>"%SCRIPT%"
echo Write-Host "Activating Node.js LTS via nvm..." -ForegroundColor Cyan>>"%SCRIPT%"
echo nvm use lts 2^>^$null>>"%SCRIPT%"
echo Refresh-SetupEnvironment>>"%SCRIPT%"
echo if (-not (Get-Command node -ErrorAction SilentlyContinue)) { throw "node is not available after nvm use lts." }>>"%SCRIPT%"
echo if (-not (Get-Command npm.cmd -ErrorAction SilentlyContinue)) { throw "npm is not available after nvm use lts." }>>"%SCRIPT%"
echo if (Get-Command codex -ErrorAction SilentlyContinue) { Write-Host "OpenAI Codex CLI already available, skipping npm global install..." -ForegroundColor Yellow } else { Install-NpmGlobalPackage "@openai/codex" "OpenAI Codex CLI" ^| Out-Null }>>"%SCRIPT%"
echo if (Get-Command copilot.cmd -ErrorAction SilentlyContinue) { Write-Host "GitHub Copilot CLI already available, skipping npm global install..." -ForegroundColor Yellow } else { Install-NpmGlobalPackage "@github/copilot" "GitHub Copilot CLI" ^| Out-Null }>>"%SCRIPT%"
echo if (Get-Command copilot.cmd -ErrorAction SilentlyContinue) {>>"%SCRIPT%"
echo     Write-Host "Standalone GitHub Copilot CLI already available; skipping gh-copilot extension install." -ForegroundColor Yellow>>"%SCRIPT%"
echo } else {>>"%SCRIPT%"
echo     Write-Host "Installing GitHub Copilot gh extension..." -ForegroundColor Cyan>>"%SCRIPT%"
echo     $ghAuth = Start-Process -FilePath "cmd.exe" -ArgumentList "/c gh auth status >nul 2>nul" -Wait -NoNewWindow -PassThru>>"%SCRIPT%"
echo     if ($ghAuth.ExitCode -eq 0) {>>"%SCRIPT%"
echo         $ghExtensions = ^& gh extension list 2^>^$null>>"%SCRIPT%"
echo         if ($ghExtensions -match 'gh-copilot') {>>"%SCRIPT%"
echo             Write-Host "gh-copilot extension already installed, skipping..." -ForegroundColor Yellow>>"%SCRIPT%"
echo         } else {>>"%SCRIPT%"
echo             try {>>"%SCRIPT%"
echo                 ^& gh extension install github/gh-copilot 1^>^$null 2^>^$null>>"%SCRIPT%"
echo                 if ($LASTEXITCODE -eq 0) {>>"%SCRIPT%"
echo                     Write-Host "gh-copilot extension installed." -ForegroundColor Green>>"%SCRIPT%"
echo                 } else {>>"%SCRIPT%"
echo                     Write-Host "gh-copilot extension install failed with exit code $LASTEXITCODE. Continuing setup." -ForegroundColor Yellow>>"%SCRIPT%"
echo                 }>>"%SCRIPT%"
echo             } catch {>>"%SCRIPT%"
echo                 Write-Host "gh-copilot extension install failed: $($_.Exception.Message). Continuing setup." -ForegroundColor Yellow>>"%SCRIPT%"
echo             }>>"%SCRIPT%"
echo         }>>"%SCRIPT%"
echo     } else {>>"%SCRIPT%"
echo         Write-Host "GitHub CLI is not authenticated; skipping gh-copilot extension install." -ForegroundColor Yellow>>"%SCRIPT%"
echo     }>>"%SCRIPT%"
echo }>>"%SCRIPT%"
echo Write-Host "`n Node.js setup complete." -ForegroundColor Green>>"%SCRIPT%"
powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%"
if %errorLevel% neq 0 (
    echo.
    echo Node setup failed with exit code %errorLevel%.
    echo Generated script: %SCRIPT%
)
endlocal
