tunnel: c552cb9c-62bd-4c8b-9ec6-16627b1b8af3
credentials-file: C:\Users\Heiner\.cloudflared\c552cb9c-62bd-4c8b-9ec6-16627b1b8af3.json
protocol: http2

ingress:
  - hostname: ffxivbe.org
    service: http://127.0.0.1:9000
  - hostname: www.ffxivbe.org
    service: http://127.0.0.1:9000
  - hostname: landing.ffxivbe.org
    service: http://127.0.0.1:5004
  - hostname: auth.ffxivbe.org
    service: http://127.0.0.1:5000
  - hostname: store.ffxivbe.org
    service: http://127.0.0.1:5001
  - hostname: admin.ffxivbe.org
    service: http://127.0.0.1:5002
  - hostname: playground.ffxivbe.org
    service: http://127.0.0.1:5003
  - hostname: payments.ffxivbe.org
    service: http://127.0.0.1:5005
  - hostname: studio.ffxivbe.org
    service: http://127.0.0.1:5006
  - hostname: supabase.ffxivbe.org
    service: http://127.0.0.1:54321
  - hostname: supabase-studio.ffxivbe.org
    service: http://127.0.0.1:54323
  - hostname: mailpit.ffxivbe.org
    service: http://127.0.0.1:54324
  - hostname: chat.ffxivbe.org
    service: http://127.0.0.1:3000
  - service: http_status:404
