@echo off
if /I "%PCSETUP_CI%"=="1" goto :after_admin_check
:: Auto-elevate to Administrator (preserving the chosen action across elevation)
powershell -NoProfile -ExecutionPolicy Bypass -Command "$p = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent()); if ($p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { exit 0 } else { exit 1 }" >nul 2>&1
if %errorlevel% neq 0 (
    :: No -ArgumentList when there is no argument: Start-Process rejects an empty string there,
    :: so a plain double-click used to fail to elevate and the window just closed.
    if "%~1"=="" (
        powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process '%~f0' -Verb RunAs"
    ) else (
        powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process '%~f0' -ArgumentList '%~1' -Verb RunAs"
    )
    exit /b
)
:after_admin_check

setlocal
set "PSModulePath="

:: Accepts "backup" or "restore" as an argument so it can run unattended, per the repo's
:: no-pauses rule. With no argument it still prompts, which is the interactive convenience path.
set "ACTION=%~1"
if /I "%ACTION%"=="backup"  goto :have_action
if /I "%ACTION%"=="restore" goto :have_action
if /I "%ACTION%"=="1" set "ACTION=backup" & goto :have_action
if /I "%ACTION%"=="2" set "ACTION=restore" & goto :have_action

echo.
echo  Start Menu Backup/Restore Tool
echo  ===============================
echo.
echo  [1] Backup current Start Menu layout
echo  [2] Restore Start Menu layout from backup
echo.
set "choice="
set /p choice="Select option (1 or 2): "
if "%choice%"=="1" set "ACTION=backup"
if "%choice%"=="2" set "ACTION=restore"
if not defined ACTION (
    echo Invalid option. Pass "backup" or "restore" to run unattended.
    endlocal & exit /b 1
)

:have_action
set "PCSETUP_SM_ACTION=%ACTION%"
set "PCSETUP_SM_BACKUP=%~dp0start-menu-backup.bin"
set "PCSETUP_SM_SHORTCUTS=%~dp0start-menu-shortcuts"

set "SCRIPT=%TEMP%\temp-start-menu.ps1"
if exist "%SCRIPT%" del "%SCRIPT%" >nul

>"%SCRIPT%" echo $action = $env:PCSETUP_SM_ACTION
>>"%SCRIPT%" echo $backup = $env:PCSETUP_SM_BACKUP
>>"%SCRIPT%" echo $shortcuts = $env:PCSETUP_SM_SHORTCUTS
>>"%SCRIPT%" echo $startMenu = Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start2.bin'
>>"%SCRIPT%" echo $programs = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
>>"%SCRIPT%" echo # A pin of a desktop shortcut is bound to the exact .lnk file in the user's Programs folder -
>>"%SCRIPT%" echo # the one Windows writes there when a shortcut from elsewhere (Z:) is pinned. A new file with
>>"%SCRIPT%" echo # the same target and arguments gets a different AutoGenerated app ID and the pin stays lost;
>>"%SCRIPT%" echo # only the byte-identical file brings it back. That folder is on C:, so a format wiped every
>>"%SCRIPT%" echo # such pin (all the FFXIV profile launchers) while start2.bin restored fine. The shortcuts
>>"%SCRIPT%" echo # are therefore saved byte-for-byte next to the .bin. Startup is left out: restoring it
>>"%SCRIPT%" echo # would change what launches at sign-in.
>>"%SCRIPT%" echo function Get-ProgramShortcuts { param([string]$Root)
>>"%SCRIPT%" echo     foreach ($lnk in @(Get-ChildItem -LiteralPath $Root -Recurse -Filter '*.lnk' -File -ErrorAction SilentlyContinue)) {
>>"%SCRIPT%" echo         $rel = $lnk.FullName.Substring($Root.TrimEnd('\').Length + 1)
>>"%SCRIPT%" echo         if ($rel -like 'Startup\*') { continue }
>>"%SCRIPT%" echo         [pscustomobject]@{ Path = $lnk.FullName; Rel = $rel }
>>"%SCRIPT%" echo     }
>>"%SCRIPT%" echo }
>>"%SCRIPT%" echo.
>>"%SCRIPT%" echo if ($action -eq 'backup') {
>>"%SCRIPT%" echo     Write-Host "Backing up Start Menu layout..." -ForegroundColor Cyan
>>"%SCRIPT%" echo     if (-not (Test-Path $startMenu)) { Write-Host "Start Menu file not found: $startMenu" -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo     try { Copy-Item $startMenu $backup -Force -ErrorAction Stop } catch { Write-Host "Backup failed: $($_.Exception.Message)" -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo     # Verify by size, not by the copy not throwing: a 0-byte backup would restore an
>>"%SCRIPT%" echo     # empty Start Menu and the old script would still have printed SUCCESS.
>>"%SCRIPT%" echo     if (-not (Test-Path $backup) -or (Get-Item $backup).Length -lt 1) { Write-Host "Backup file is missing or empty." -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo     if ((Get-Item $backup).Length -ne (Get-Item $startMenu).Length) { Write-Host "Backup size does not match the source." -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo     Write-Host "Backed up $((Get-Item $backup).Length) bytes to $backup" -ForegroundColor Green
>>"%SCRIPT%" echo     # Shortcuts: build the new set beside the old one and swap, so a failed copy never
>>"%SCRIPT%" echo     # leaves a half-written folder where the last good one was.
>>"%SCRIPT%" echo     $staging = "$shortcuts.new"
>>"%SCRIPT%" echo     if (Test-Path -LiteralPath $staging) { Remove-Item -LiteralPath $staging -Recurse -Force }
>>"%SCRIPT%" echo     $items = @(Get-ProgramShortcuts -Root $programs)
>>"%SCRIPT%" echo     try {
>>"%SCRIPT%" echo         foreach ($item in $items) {
>>"%SCRIPT%" echo             $dest = Join-Path $staging $item.Rel
>>"%SCRIPT%" echo             $null = New-Item -ItemType Directory -Path (Split-Path $dest -Parent) -Force -ErrorAction Stop
>>"%SCRIPT%" echo             Copy-Item -LiteralPath $item.Path -Destination $dest -Force -ErrorAction Stop
>>"%SCRIPT%" echo         }
>>"%SCRIPT%" echo     } catch { Write-Host "Shortcut backup failed: $($_.Exception.Message)" -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo     $copied = @(Get-ProgramShortcuts -Root $staging)
>>"%SCRIPT%" echo     if ($copied.Count -ne $items.Count) { Write-Host "Shortcut backup incomplete: $($copied.Count) of $($items.Count) copied." -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo     if (Test-Path -LiteralPath $shortcuts) { Remove-Item -LiteralPath $shortcuts -Recurse -Force }
>>"%SCRIPT%" echo     if ($copied.Count -gt 0) { Move-Item -LiteralPath $staging -Destination $shortcuts }
>>"%SCRIPT%" echo     Write-Host "Backed up $($copied.Count) Start Menu shortcuts to $shortcuts" -ForegroundColor Green
>>"%SCRIPT%" echo     exit 0
>>"%SCRIPT%" echo }
>>"%SCRIPT%" echo.
>>"%SCRIPT%" echo Write-Host "Restoring Start Menu layout..." -ForegroundColor Cyan
>>"%SCRIPT%" echo if (-not (Test-Path $backup)) {
>>"%SCRIPT%" echo     Write-Host "Backup file not found: $backup" -ForegroundColor Red
>>"%SCRIPT%" echo     Write-Host "Run this script with 'backup' first." -ForegroundColor Yellow
>>"%SCRIPT%" echo     exit 1
>>"%SCRIPT%" echo }
>>"%SCRIPT%" echo if ((Get-Item $backup).Length -lt 1) { Write-Host "Backup file is empty; refusing to restore." -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo $dir = Split-Path $startMenu -Parent
>>"%SCRIPT%" echo if (-not (Test-Path $dir)) { Write-Host "Start Menu state folder not found: $dir" -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo # Write FIRST, then restart Start. Windows relaunches StartMenuExperienceHost within a
>>"%SCRIPT%" echo # second of it being stopped, and the running host re-saves its in-memory layout over
>>"%SCRIPT%" echo # start2.bin - so the old "stop, wait 2 s, copy" order lost the race and the restored
>>"%SCRIPT%" echo # file was overwritten with the pins it was meant to replace. Stopping it after the copy
>>"%SCRIPT%" echo # makes the fresh host read the new file. Size is checked before the restart, because
>>"%SCRIPT%" echo # the host re-encodes the file on start (same pins, different bytes and size).
>>"%SCRIPT%" echo # Shortcuts go back BEFORE the layout loads: a pin whose .lnk is missing at that moment is
>>"%SCRIPT%" echo # dropped. An existing file is overwritten when it differs, since an installer- or
>>"%SCRIPT%" echo # Scoop-made copy of the same name is a different file and would not match the pin. A
>>"%SCRIPT%" echo # shortcut whose target no longer exists is skipped rather than restored as a dead link.
>>"%SCRIPT%" echo $restored = 0; $same = 0; $skipped = 0; $failed = 0
>>"%SCRIPT%" echo if (Test-Path -LiteralPath $shortcuts) {
>>"%SCRIPT%" echo     $ws = New-Object -ComObject WScript.Shell
>>"%SCRIPT%" echo     foreach ($item in @(Get-ProgramShortcuts -Root $shortcuts)) {
>>"%SCRIPT%" echo         $dest = Join-Path $programs $item.Rel
>>"%SCRIPT%" echo         $target = $ws.CreateShortcut($item.Path).TargetPath
>>"%SCRIPT%" echo         if ($target -and -not (Test-Path -LiteralPath $target)) { $skipped++; Write-Host "  skipped, target missing: $($item.Rel)" -ForegroundColor DarkYellow; continue }
>>"%SCRIPT%" echo         if ((Test-Path -LiteralPath $dest) -and (Get-FileHash -LiteralPath $dest).Hash -eq (Get-FileHash -LiteralPath $item.Path).Hash) { $same++; continue }
>>"%SCRIPT%" echo         try {
>>"%SCRIPT%" echo             $null = New-Item -ItemType Directory -Path (Split-Path $dest -Parent) -Force -ErrorAction Stop
>>"%SCRIPT%" echo             Copy-Item -LiteralPath $item.Path -Destination $dest -Force -ErrorAction Stop
>>"%SCRIPT%" echo             if ((Get-FileHash -LiteralPath $dest).Hash -ne (Get-FileHash -LiteralPath $item.Path).Hash) { throw 'copy does not match the backup' }
>>"%SCRIPT%" echo             $restored++
>>"%SCRIPT%" echo         } catch { $failed++; Write-Host "  FAILED: $($item.Rel): $($_.Exception.Message)" -ForegroundColor Red }
>>"%SCRIPT%" echo     }
>>"%SCRIPT%" echo     Write-Host "Shortcuts: $restored restored, $same already in place, $skipped skipped (app not installed), $failed failed" -ForegroundColor Cyan
>>"%SCRIPT%" echo } else {
>>"%SCRIPT%" echo     Write-Host "No saved shortcuts at $shortcuts - pins of shortcuts pinned from outside Start will not come back." -ForegroundColor Yellow
>>"%SCRIPT%" echo }
>>"%SCRIPT%" echo try { Copy-Item $backup $startMenu -Force -ErrorAction Stop } catch { Write-Host "Restore failed: $($_.Exception.Message)" -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo if ((Get-Item $startMenu).Length -ne (Get-Item $backup).Length) { Write-Host "Restored file size does not match the backup." -ForegroundColor Red; exit 1 }
>>"%SCRIPT%" echo Write-Host "Restarting Start Menu so it loads the restored layout..." -ForegroundColor Cyan
>>"%SCRIPT%" echo Stop-Process -Name StartMenuExperienceHost -Force -ErrorAction SilentlyContinue
>>"%SCRIPT%" echo Write-Host "Start Menu layout restored. Press the Windows key to see it." -ForegroundColor Green
>>"%SCRIPT%" echo if ($failed -gt 0) { exit 1 }

powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%"
set "SM_EXIT=%errorlevel%"
if %SM_EXIT% neq 0 (
    echo.
    echo Start Menu %ACTION% finished with exit code %SM_EXIT%.
) else (
    del "%SCRIPT%" >nul 2>&1
)
endlocal & exit /b %SM_EXIT%
